CREATE TABLE IF NOT EXISTS import_batches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  owner_id VARCHAR(128) NOT NULL,
  created_by_user_id VARCHAR(64) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  file_sha256 VARCHAR(64) NOT NULL,
  upload_blob LONGBLOB NOT NULL,
  display_name VARCHAR(255) NOT NULL DEFAULT '',
  accounting_year VARCHAR(16) NOT NULL DEFAULT '',
  version_label VARCHAR(64) NOT NULL DEFAULT '',
  notes TEXT NOT NULL,
  duplicate_of_batch_id INT NULL,
  supersedes_batch_id INT NULL,
  overlaps_with_batch_id INT NULL,
  is_exact_duplicate TINYINT(1) NOT NULL DEFAULT 0,
  has_period_overlap TINYINT(1) NOT NULL DEFAULT 0,
  rows_total INT NOT NULL DEFAULT 0,
  rows_valid INT NOT NULL DEFAULT 0,
  rows_invalid INT NOT NULL DEFAULT 0,
  rows_duplicate INT NOT NULL DEFAULT 0,
  rows_applied INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'uploaded',
  uploaded_at DATETIME NOT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  KEY ix_import_batches_owner_id (owner_id),
  KEY ix_import_batches_file_sha256 (file_sha256),
  KEY ix_import_batches_created_by_user_id (created_by_user_id),
  KEY ix_import_batches_status (status)
);

CREATE TABLE IF NOT EXISTS import_rows (
  id INT AUTO_INCREMENT PRIMARY KEY,
  batch_id INT NOT NULL,
  row_no INT NOT NULL,
  excel_sheet_name VARCHAR(255) NOT NULL DEFAULT '',
  excel_row_ref VARCHAR(64) NOT NULL DEFAULT '',
  raw_payload_json TEXT NOT NULL,
  normalized_payload_json TEXT NOT NULL,
  account_uid VARCHAR(128) NOT NULL DEFAULT '',
  abonent_id VARCHAR(128) NOT NULL DEFAULT '',
  account_number VARCHAR(128) NOT NULL DEFAULT '',
  payment_date VARCHAR(10) NOT NULL DEFAULT '',
  paid_date VARCHAR(10) NOT NULL DEFAULT '',
  payment_period VARCHAR(7) NOT NULL DEFAULT '',
  charge_year VARCHAR(4) NOT NULL DEFAULT '',
  charge_month VARCHAR(2) NOT NULL DEFAULT '',
  amount VARCHAR(32) NOT NULL DEFAULT '',
  source_index INT NULL,
  source_label VARCHAR(255) NOT NULL DEFAULT '',
  fingerprint VARCHAR(64) NOT NULL DEFAULT '',
  matched_payment_id VARCHAR(64) NOT NULL DEFAULT '',
  applied_at DATETIME NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'parsed',
  reason_code VARCHAR(64) NOT NULL DEFAULT '',
  reason_text VARCHAR(1024) NOT NULL DEFAULT '',
  error_details_json TEXT NOT NULL,
  KEY ix_import_rows_batch_id (batch_id),
  KEY ix_import_rows_account_uid (account_uid),
  KEY ix_import_rows_fingerprint (fingerprint),
  KEY ix_import_rows_status (status),
  CONSTRAINT fk_import_rows_batch FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payment_audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  owner_id VARCHAR(128) NOT NULL,
  batch_id INT NOT NULL,
  row_id INT NULL,
  action VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  details_json TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ix_payment_audit_log_owner_id (owner_id),
  KEY ix_payment_audit_log_batch_id (batch_id),
  KEY ix_payment_audit_log_row_id (row_id)
);
