CREATE TABLE IF NOT EXISTS payment_ledger_store_audit (
  id BIGINT NOT NULL AUTO_INCREMENT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  owner_id VARCHAR(128) NOT NULL,
  actor_id VARCHAR(128) NOT NULL DEFAULT '',
  storage_key VARCHAR(255) NOT NULL,
  account_uid VARCHAR(128) NOT NULL,
  action VARCHAR(16) NOT NULL,
  endpoint VARCHAR(128) NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  source VARCHAR(128) NOT NULL DEFAULT 'UNKNOWN',
  old_rows_count INT NULL,
  new_rows_count INT NULL,
  old_value_present TINYINT(1) NOT NULL DEFAULT 0,
  new_value_present TINYINT(1) NOT NULL DEFAULT 0,
  guard_result VARCHAR(32) NOT NULL DEFAULT 'NOT_APPLICABLE',
  guard_reason VARCHAR(128) NOT NULL DEFAULT '',
  http_status INT NOT NULL,
  full_recalc_lock_present TINYINT(1) NOT NULL DEFAULT 0,
  calculated_final_empty TINYINT(1) NOT NULL DEFAULT 0,
  payload_size INT NOT NULL DEFAULT 0,
  details_json TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payment_ledger_store_audit_request_id (request_id),
  KEY ix_payment_ledger_store_audit_owner_created (owner_id, created_at),
  KEY ix_payment_ledger_store_audit_owner_uid_created (owner_id, account_uid, created_at),
  KEY ix_payment_ledger_store_audit_storage_key (storage_key),
  KEY ix_payment_ledger_store_audit_action (action)
);
